<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>promise with .then and catch</title>
</head>
<body>
    
    <script>
        let p1 = new Promise((resolve,reject)=>{
            setTimeout(() => {
                resolve(10);
            }, 3000);
        })
        p1.then((value)=>{
            console.log(value);
        })
        
        let p2 = new Promise((resolve,reject)=>{
            setTimeout(() => {
                reject(new Error("error occur in promise p2"))
            }, 6000);
        })
        //use of catch syntax
        p2.catch((error)=>{
            console.log("some error occur in promise p2...");
        })
        // p2.then((value)=>{
        //     console.log(value);
        // })
    </script>
</body>
</html>